# Disable Pi swapfile to help with SD card health

- name: Disable swap via swapoff command
  ansible.builtin.command: swapoff --all

- name: Remove dphys-swapfile package
  ansible.builtin.apt:
    name: dphys-swapfile
    state: absent
