- name: Ensure git is installed
  ansible.builtin.apt:
    name: git
    state: present

- name: Set git default branch name to 'main'
  ansible.builtin.command: git config --global init.defaultBranch main
