- hosts: pis
  roles:
    - wifi-country
    - disable-bluetooth
    - git
    - bash-mods
    - docker
    - role: hashicorp
      binaries:
        - nomad
        - consul
    - role: swapfile
      enabled: no
