# Sets the Pi Wi-Fi Country to disable the login warning message

- name: Check current Wi-Fi Country
  ansible.builtin.command: raspi-config nonint get_wifi_country
  changed_when: false
  register: wifi_country

- name: Set Wi-Fi Country to United Kingdom (GB)
  ansible.builtin.command: raspi-config nonint do_wifi_country GB
  when: wifi_country.stdout != 'GB'
